# ==================================================
# 0. IMPORTACIÓN DE LIBRERIAS
# ==================================================

In [4]:
# Importo Pandas y NumPy para la manipulación y análisis de datos.
# Los gráficos se desarrollarán posteriormente en Power BI, por lo que no es necesario importar Matplotlib ni Seaborn en esta fase.

import pandas as pd
import numpy as np

In [5]:
# Configuración de Pandas para mostrar todas las columnas del DataFrame

pd.set_option('display.max_columns', None)

# ==================================================
# 1. CARGA DE DATOS
# ==================================================

In [6]:
ruta = "/Users/bewis/Desktop/Curso Analytics/__Proyecto final/Data/Raw/"

orders = pd.read_csv(ruta + "olist_orders_dataset.csv")
customers = pd.read_csv(ruta + "olist_customers_dataset.csv")
items = pd.read_csv(ruta + "olist_order_items_dataset.csv")
products = pd.read_csv(ruta + "olist_products_dataset.csv")
payments = pd.read_csv(ruta + "olist_order_payments_dataset.csv")

# ==================================================
# 2. EXPLORACIÓN INICIAL DE LOS DATASETS
# ==================================================

In [7]:
# Compruebo que se han cargado bien

print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Items:", items.shape)
print("Products:", products.shape)
print("Payments:", payments.shape)

Orders: (99441, 8)
Customers: (99441, 5)
Items: (112650, 7)
Products: (32951, 9)
Payments: (103886, 5)

In [8]:
# Reviso las columnas de cada dataset

print(orders.columns)
print()
print(customers.columns)
print()
print(items.columns)
print()
print(products.columns)
print()
print(payments.columns)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [9]:
orders.info()
customers.info()
items.info()
products.info()
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

# ==================================================
# 3. AUDITORÍA DE LOS DATASETS
# ==================================================

# 3.1 AUDITORÍA DE ORDERS

In [10]:
# Reviso las primeras filas para comprender la estructura de la tabla.

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [11]:
# Compruebo si hay nulos en orders y reviso el por qué

orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [12]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [13]:
orders[orders['order_approved_at'].isnull()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [14]:
orders[orders['order_delivered_carrier_date'].isnull()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [15]:
orders[orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [16]:
# Conclusión:
# Los valores nulos corresponden principalmente a pedidos cancelados,
# enviados o en proceso, por lo que no se consideran errores de calidad
# y se mantendrán en el dataset.

# Analizo los pedidos entregados sin fecha de entrega

orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [17]:
# Compruebo si existen filas completamente duplicadas.

orders.duplicated().sum()

np.int64(0)

In [18]:
# Compruebo si order_id es único en la tabla orders

orders['order_id'].duplicated().sum()

np.int64(0)

In [19]:
# Conclusión:
# La tabla orders no contiene filas duplicadas y cada pedido (order_id)
# es único, por lo que no es necesario eliminar registros.

In [20]:
# Reviso si los datos, especialmente las fechas, están almacenadas correctamente

orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [21]:
# Convierto las columnas de fecha al tipo datetime

date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [22]:
# Reviso la distribución de los estados de los pedidos

orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

# 3.2 AUDITORÍA DE LA TABLA CUSTOMERS

In [23]:
# Reviso las primeras filas para comprender la estructura de la tabla.

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [24]:
# Compruebo si existen valores nulos

customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [25]:
# Compruebo si existen filas completamente duplicadas.

customers.duplicated().sum()

np.int64(0)

In [26]:
# Compruebo si customer_id es único

customers["customer_id"].duplicated().sum()

np.int64(0)

In [27]:
# Compruebo si customer_unique_id es único

customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [28]:
# Conclusiones:
# - No existen valores nulos en la tabla customers.
# - No existen filas duplicadas.
# - customer_id es único para cada registro y representa el identificador
#   del cliente asociado a un pedido concreto.
# - customer_unique_id presenta 3.345 valores duplicados, lo cual es esperable,
#   ya que identifica al cliente de forma única y permite detectar clientes
#   que han realizado más de un pedido.

In [29]:
# Reviso si los datos están almacenadas correctamente

customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [30]:
# Conclusión:
# Todos los tipos de datos son adecuados para el análisis.
# No es necesario realizar conversiones de tipo en esta tabla.

# 3.3 AUDITORÍA DE LA TABLA ITEMS

In [31]:
# Reviso las primeras filas para comprender la estructura de la tabla.

items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [32]:
# Compruebo si existen valores nulos

items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [33]:
# Compruebo si existen filas completamente duplicadas.

items.duplicated().sum()

np.int64(0)

In [34]:
# Compruebo si existen valores duplicados en order_id

items["order_id"].duplicated().sum()

np.int64(13984)

In [35]:
# Compruebo si existen valores duplicados en product_id

items["product_id"].duplicated().sum()

np.int64(79699)

In [36]:
# Compruebo si existen valores duplicados en order_id + product_id

items.duplicated(subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [37]:
# Conclusión:
# order_id y product_id pueden aparecer repetidos porque un mismo pedido puede contener
# varios productos y un mismo producto puede venderse en muchos pedidos.
# La combinación order_id + order_item_id debe identificar cada línea de pedido.

In [38]:
# Reviso si los datos, especialmente las fechas, están almacenadas correctamente

items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [39]:
# Convierto la columna de fecha al tipo datetime

items["shipping_limit_date"] = pd.to_datetime(items["shipping_limit_date"])

In [40]:
items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [41]:
# Conclusión:
# Todos los tipos de datos son correctos excepto shipping_limit_date,
# que inicialmente estaba almacenada como texto y se ha convertido
# al tipo datetime para facilitar futuros análisis temporales.

# 3.4 AUDITORÍA DE LA TABLA PRODUCTS

In [42]:
# Reviso las primeras filas para comprender la estructura de la tabla.

products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [43]:
# Compruebo si existen valores nulos en la tabla products.

products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [44]:
# Compruebo si los 610 registros con categoría nula
# también tienen el resto de atributos descriptivos nulos.

products[
    products["product_category_name"].isnull()
].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [45]:
# Compruebo cuántos productos presentan simultáneamente
# los cuatro campos descriptivos nulos.

products[
    products["product_category_name"].isnull() &
    products["product_name_lenght"].isnull() &
    products["product_description_lenght"].isnull() &
    products["product_photos_qty"].isnull()
].shape

(610, 9)

In [46]:
# Analizo los productos que no tienen información sobre peso y dimensiones.

products[
    products["product_weight_g"].isnull()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
# Conclusión:
# Se detectan dos grupos diferenciados de valores nulos:
#
# - 610 productos carecen de información descriptiva
#   (categoría, longitud del nombre, descripción y número de fotografías).
#
# - 2 productos no presentan información sobre peso y dimensiones.
#
# Ambos casos se revisarán durante la fase de limpieza antes de decidir
# si deben mantenerse o eliminarse.

In [48]:
# Compruebo si existen filas completamente duplicadas.

products.duplicated().sum()

np.int64(0)

In [49]:
# Compruebo si product_id identifica de forma única cada producto.

products["product_id"].duplicated().sum()

np.int64(0)

In [50]:
# Conclusión:
# product_id identifica de forma única cada producto,
# por lo que puede utilizarse como clave para unir esta tabla
# con la tabla order_items.

In [51]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [52]:
# Conclusión:
# La mayoría de los tipos de datos son correctos.
# Las columnas product_name_lenght, product_description_lenght y
# product_photos_qty aparecen como float64 debido a la presencia
# de valores nulos. Se revisarán durante la fase de limpieza para
# decidir si es necesario convertirlas al tipo entero.

# 3.5 AUDITORÍA DE LA TABLA PAYMENTS

In [53]:
# Reviso las primeras filas para comprender la estructura de la tabla.

payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [54]:
# Compruebo si existen valores nulos en la tabla payments.

payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [55]:
# Compruebo si existen filas completamente duplicadas.

payments.duplicated().sum()

np.int64(0)

In [56]:
# Compruebo si existen pedidos con más de un registro de pago.

payments["order_id"].duplicated().sum()

np.int64(4446)

In [57]:
# Conclusión:
# order_id presenta valores duplicados, lo cual es esperable,
# ya que un mismo pedido puede estar asociado a varios registros
# de pago cuando el cliente utiliza más de un método de pago
# o divide el importe en varias transacciones.

In [58]:
# Compruebo si la combinación order_id + payment_sequential
# identifica de forma única cada pago.

payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

np.int64(0)

In [59]:
# Conclusión:
# La combinación de las columnas order_id y payment_sequential
# identifica de forma única cada registro de pago, por lo que
# puede utilizarse como clave compuesta de esta tabla.

In [60]:
# Reviso si los datos están almacenados correctamente.

payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [61]:
# Analizo los métodos de pago utilizados.

payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

# ==================================================
# 4. LIMPIEZA DE LOS DATOS
# ==================================================

# 4.1 LIMPIEZA DE ORDERS

In [62]:
# Analizo los pedidos entregados que no tienen fecha de entrega
# para comprobar si presentan otras anomalías.

orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [63]:
# Elimino los pedidos con estado "delivered" que no disponen de fecha
# de entrega. Estos registros representan únicamente 8 observaciones
# (0,008 % del total) y no permiten calcular correctamente las métricas
# relacionadas con los tiempos de entrega.

orders = orders[
    ~(
        (orders["order_status"] == "delivered") &
        (orders["order_delivered_customer_date"].isnull())
    )
]

In [64]:
# Compruebo si se han eliminado

orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isnull())
]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [65]:
# Conclusión:
# Se eliminan 8 pedidos con estado "delivered" que no disponían de
# fecha de entrega. Dado que representan un porcentaje muy reducido
# del conjunto de datos (0,008 %), su eliminación no afecta a la
# representatividad del análisis y permite calcular correctamente
# las métricas relacionadas con los tiempos de entrega.

In [66]:
# Analizo los pedidos que no tienen fecha de aprobación.

orders[orders["order_approved_at"].isnull()]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [67]:
# Analizo los pedidos entregados (delivered) que no tienen fecha de aprobación.

orders[
    (orders["order_status"] == "delivered") &
    (orders["order_approved_at"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31

In [68]:
# Se detectan 14 pedidos con estado "delivered" que no disponen de
# fecha de aprobación. Dado que todos ellos presentan fechas de envío
# y entrega, se considera que la aprobación del pedido tuvo lugar.
#
# Para evitar la pérdida de estos registros y mantener la coherencia
# temporal del análisis, se sustituye la fecha de aprobación por la
# fecha de compra del pedido. Esta decisión afecta únicamente al
# 0,014 % del conjunto de datos.

# Sustituyo la fecha de aprobación por la fecha de compra
# en los pedidos entregados que no disponen de fecha de aprobación.

mask = (
    (orders["order_status"] == "delivered") &
    (orders["order_approved_at"].isnull())
)

orders.loc[mask, "order_approved_at"] = orders.loc[
    mask, "order_purchase_timestamp"
]

In [69]:
# Compruebo que ya no existen pedidos entregados sin fecha de aprobación.

orders[
    (orders["order_status"] == "delivered") &
    (orders["order_approved_at"].isnull())
]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [70]:
# Analizo los pedidos que no tienen fecha de entrega.

orders[
    orders["order_delivered_customer_date"].isnull()
]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
created           5
approved          2
Name: count, dtype: int64

In [71]:
# Conclusión:
# Los valores nulos restantes en la columna order_delivered_customer_date
# corresponden exclusivamente a pedidos que no llegaron a entregarse
# (cancelados, no disponibles o aún en proceso de envío).
#
# Estos valores nulos representan correctamente el estado del pedido,
# por lo que se mantienen y no se realiza ninguna imputación.

# 4.2 LIMPIEZA DE CUSTOMERS

In [72]:
# Compruebo los estados presentes en el dataset.

customers["customer_state"].sort_values().unique()

<StringArray>
['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT',
 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP',
 'TO']
Length: 27, dtype: str

In [73]:
# Conclusión:
# Tras revisar la tabla customers, no se detectan incidencias que
# requieran limpieza. La tabla no presenta valores nulos ni registros
# duplicados y los tipos de datos son correctos.
#
# Se mantiene la estructura original del dataset sin realizar
# modificaciones.

# 4.3 LIMPIEZA DE ITEMS

In [74]:
# Compruebo si existen productos con precio menor o igual que cero.

items[items["price"] <= 0]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [75]:
# Conclusión:
# No existen productos con precio menor o igual que cero.

In [76]:
# Conclusión:
# La tabla items no requiere procesos de limpieza adicionales.
#
# No se detectan valores nulos, registros duplicados ni inconsistencias
# en los identificadores. Asimismo, los importes de los productos y los
# costes de envío presentan valores válidos, por lo que se mantiene la
# estructura original del dataset.

# 4.4 LIMPIEZA DE PRODUCTS

In [77]:
# Obtengo los productos que no disponen de información descriptiva.

products_null = products[
    products["product_category_name"].isnull()
]

products_null.shape

(610, 9)

In [78]:
# Compruebo cuántos de estos productos aparecen en la tabla items.

items[
    items["product_id"].isin(products_null["product_id"])
].shape

(1603, 7)

In [83]:
# Compruebo cuántos productos presentan simultáneamente
# los cuatro atributos descriptivos nulos.

(
    products[
        products["product_category_name"].isnull() &
        products["product_name_lenght"].isnull() &
        products["product_description_lenght"].isnull() &
        products["product_photos_qty"].isnull()
    ]
).shape

(610, 9)

In [79]:
# Conclusión:
# Se detectan 610 productos sin información descriptiva, lo que supone
# aproximadamente un 1,85 % del catálogo de productos.
#
# Sin embargo, estos productos aparecen en 1.603 líneas de pedido,
# por lo que forman parte de ventas reales y no deben eliminarse,
# ya que supondría la pérdida de información relevante para el análisis.
#
# Se decide mantener estos registros y sustituir únicamente la categoría
# nula por el valor "Unknown", permitiendo identificar estos productos
# durante el análisis y el desarrollo del dashboard.

In [84]:
# Sustituyo los valores nulos de la categoría por "Unknown".
# Se trata de productos vendidos que no disponen de información
# sobre su categoría, por lo que se crea una categoría específica
# para identificarlos durante el análisis.

products["product_category_name"] = products[
    "product_category_name"
].fillna("Unknown")

In [85]:
# Compruebo que ya no existen valores nulos en la categoría del producto.

products["product_category_name"].isnull().sum()

np.int64(0)

In [ ]:
# Conclusión:
# Se sustituyen los valores nulos de product_category_name por "Unknown"
# para mantener estos productos en el análisis y poder aprovechar las
# filas de venta asociadas.
#
# No se modifican las columnas product_name_lenght,
# product_description_lenght y product_photos_qty, ya que son variables
# numéricas y no es posible estimar sus valores de forma fiable.

In [86]:
# Obtengo los productos sin información sobre peso y dimensiones.

products_dimensions_null = products[
    products["product_weight_g"].isnull()
]

products_dimensions_null

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
# Compruebo si estos productos aparecen en la tabla items.

items[
    items["product_id"].isin(products_dimensions_null["product_id"])
]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
7098,101157d4fae1c9fb74a00a5dee265c25,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 08:02:26,29.0,14.52
9233,1521c6bb7b1028154c8c67cf80fa809f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:10:16,29.0,16.05
28715,415cfaaaa8cea49f934470548797fed1,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
28716,415cfaaaa8cea49f934470548797fed1,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
39299,595316a07cd3dea9db7adfcc7e247ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-18 04:26:04,39.0,9.27
48424,6e150190fbe04c642a9cf0b80d83ee16,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-30 16:45:14,39.0,16.79
48980,6f497c40431d5fb0cfbd6c943dd29215,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 05:55:32,29.0,10.96
58833,85f8ad45e067abd694b627859fa57453,1,09ff539a621711667c43eba6a3bd8466,8b8cfc8305aa441e4239358c9f6f2485,2017-02-03 21:40:02,1934.0,27.00
71134,a2456e7f02197951664897a94c87242d,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 11:50:09,29.0,24.84
73556,a7a43f469c0d7bdb0a23a82db125aefa,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-28 13:15:11,39.0,15.10
82767,bbfc7badbed2f1828e22b6d629201bd4,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-18 04:04:10,39.0,11.85
84199,bf49f84a0580ef6751e13357776b7ed9,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-09 21:35:18,39.0,15.10
85060,c1424efcde3c9e9febd9e1761667789e,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-14 02:45:36,29.0,14.52
93346,d38dcb503cd4ddc6ce7702552918bd8f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
93347,d38dcb503cd4ddc6ce7702552918bd8f,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
97847,ddf16d77e858a32f36e10c289a28ef61,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-05-02 10:50:08,29.0,14.52
100495,e3daea0200104991cb979c2fcc509ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 14:22:36,29.0,10.96
103715,eb855beb3ac99461f7a076b4c3652472,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-03-30 16:03:46,29.0,14.52

In [ ]:
# Conclusión:
# Los 2 productos sin información sobre peso y dimensiones aparecen
# en pedidos reales, por lo que no se eliminan del conjunto de datos.
#
# Se mantienen los valores nulos, ya que representan un porcentaje
# muy reducido del dataset (0,006%) y no existe un criterio objetivo para
# imputar sus dimensiones sin introducir información ficticia.

# 4.5 LIMPIEZA DE PAYMENTS

In [88]:
# Compruebo si existen pagos con importe menor o igual que cero.

payments[payments["payment_value"] <= 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [90]:
# Reviso todos los pagos asociados a los pedidos con importe igual a 0.

payments[
    payments["order_id"].isin(
        payments.loc[payments["payment_value"] == 0, "order_id"]
    )
].sort_values(["order_id", "payment_sequential"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.00
33781,45ed6e85398a87c253db47c2d9f48216,1,voucher,1,21.13
11755,45ed6e85398a87c253db47c2d9f48216,2,voucher,1,50.01
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.00
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.00
40546,6ccb433e00daae1283ccc956189c82ae,1,credit_card,5,84.67
93478,6ccb433e00daae1283ccc956189c82ae,2,voucher,1,14.65
92318,6ccb433e00daae1283ccc956189c82ae,3,voucher,1,22.72
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.00
20963,8bcbe01d44d147f901cd3192671144db,1,credit_card,1,36.21
63762,8bcbe01d44d147f901cd3192671144db,2,voucher,1,31.70
5163,8bcbe01d44d147f901cd3192671144db,3,voucher,1,6.25
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.00
44891,b23878b3e8eb4d25a158f57d96331b18,1,credit_card,1,35.98
55494,b23878b3e8eb4d25a158f57d96331b18,2,voucher,1,122.79
72011,b23878b3e8eb4d25a158f57d96331b18,3,voucher,1,12.80
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.00
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.00
14321,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.71
23074,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.51
65641,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.95
9985,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.16
28330,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.66
29648,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.02
82593,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.32
68853,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.02
17274,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.08
19565,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.86
32519,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.03
73537,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.60
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
63369,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.04
78050,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.86
79670,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.72
80321,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.73
74721,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.02
93337,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.00
74239,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.11
100606,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.03
85166,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.86
99213,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.42
24879,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.68
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

In [91]:
# Analizo el estado de los pedidos cuyo único pago es 0 €.

orders[
    orders["order_id"].isin(
        payments.loc[
            (payments["payment_value"] == 0) &
            (payments["payment_type"] == "not_defined"),
            "order_id"
        ]
    )
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12
39919,4637ca194b6387e2d538dc89b124b0ee,a73c1f73f5772cf801434bf984b0b1a7,canceled,2018-09-03 14:14:25,NaT,NaT,NaT,2018-09-10
40235,c8c528189310eaa44a745b8d9d26908b,197a2a6a77da93f678ea0d379f21da0a,canceled,2018-08-28 20:05:14,NaT,NaT,NaT,2018-09-11

In [89]:
# Compruebo si existen pagos con un número de cuotas inferior a 1.

payments[payments["payment_installments"] < 1]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [ ]:
# Compruebo esos dos pedidos

payments[
    payments["order_id"].isin(
        payments.loc[
            payments["payment_installments"] == 0,
            "order_id"
        ]
    )
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [93]:
# Reviso todos los pagos asociados a los pedidos
# con payment_installments igual a 0.

payments[
    payments["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
].sort_values(["order_id", "payment_sequential"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69

In [94]:
# Compruebo el estado de los dos pedidos con payment_installments = 0.

orders[
    orders["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
63782,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16
66368,1a57108394169c0b47d8f876acc9ba2d,48ebb06cf56dba9d009230cc751bb195,delivered,2018-05-15 16:25:14,2018-05-15 16:36:52,2018-05-17 12:37:00,2018-05-24 15:45:41,2018-06-06

In [96]:
# Calculo el importe total pagado (precio + transporte).

items[
    items["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
].assign(
    total=lambda x: x["price"] + x["freight_value"]
).groupby("order_id")["total"].sum()

order_id
1a57108394169c0b47d8f876acc9ba2d    129.94
744bade1fcf9ff3f31d860ace076d422     58.69
Name: total, dtype: float64

In [97]:
# Se corrigen dos registros con payment_installments = 0.
# Tras comprobar que el importe del pago coincide con el importe total
# del pedido y que solo existe un registro de pago asociado, se sustituye
# el valor 0 por 1 al considerarse un error puntual de registro.

payments.loc[
    payments["payment_installments"] == 0,
    "payment_installments"
] = 1

In [98]:
# Compruebo que ya no existen registros con payment_installments igual a 0.

payments[payments["payment_installments"] == 0]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [ ]:
# Conclusión:
# Se detectan dos pedidos entregados con payment_installments igual a 0.
# Tras comprobar que ambos pedidos presentan un único pago y que el
# importe abonado coincide con el importe total del pedido, se concluye
# que se trata de un error puntual de registro.
#
# Por este motivo, se sustituye el valor 0 por 1, indicando que el pago
# se realizó en una única cuota.

# ==================================================
# 5. INTEGRACIÓN DE LOS DATASETS
# ==================================================

In [99]:
# Creo una copia de la tabla orders para construir el dataset final
# sin modificar la tabla original.

df_final = orders.copy()

# Compruebo el tamaño inicial del dataset base.

df_final.shape

(99433, 8)

In [100]:
# Uno la información de pedidos con la información de clientes.
# La unión se realiza mediante customer_id, que está presente en ambas tablas.

df_final = df_final.merge(
    customers,
    on="customer_id",
    how="left"
)

# Compruebo el tamaño del dataset después del merge.

df_final.shape

(99433, 12)

In [101]:
# Compruebo si se han generado valores nulos en las columnas de customers
# después de realizar la unión.

df_final[
    [
        "customer_unique_id",
        "customer_zip_code_prefix",
        "customer_city",
        "customer_state"
    ]
].isnull().sum()

customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [102]:
# Añado la información de los productos incluidos en cada pedido.
# La unión se realiza mediante order_id.

df_final = df_final.merge(
    items,
    on="order_id",
    how="left"
)

# Compruebo el tamaño del dataset después de añadir items.

df_final.shape

(113417, 18)

In [103]:
# Compruebo cuántos pedidos únicos hay después del merge.

df_final["order_id"].nunique()

99433

In [ ]:
# Conclusión:
# Tras incorporar la tabla items, el número de filas aumenta de
# 99.433 a 113.417 registros. Este incremento es esperado, ya que
# un mismo pedido puede contener varios productos.
#
# El número de pedidos únicos se mantiene en 99.433, lo que confirma
# que la unión se ha realizado correctamente sin perder información.

In [104]:
# Añado la información descriptiva de los productos.
# La unión se realiza mediante product_id.

df_final = df_final.merge(
    products,
    on="product_id",
    how="left"
)

# Compruebo el tamaño del dataset tras la unión.

df_final.shape

(113417, 26)

In [105]:
# Compruebo si existen productos sin información asociada
# después de realizar la unión.

df_final["product_category_name"].isnull().sum()

np.int64(775)

In [107]:
# Compruebo si los registros sin categoría también tienen product_id nulo.

df_final[
    df_final["product_category_name"].isnull()
][["order_id", "order_status", "product_id"]].head(20)

                              order_id order_status product_id
306   8e24261a7e58791d10cb1bf9da94df5c  unavailable        NaN
671   c272bcd21c287498b4883c7512019702  unavailable        NaN
791   37553832a3a89c9b2db59701c357ca67  unavailable        NaN
850   d57e15fb07fd180f06ab3926b39edcd2  unavailable        NaN
1294  00b1cb0320190ca0daa2c88b35206009     canceled        NaN
1326  2f634e2cebf8c0283e7ef0989f77d217  unavailable        NaN
1802  ee0db22a8e742b752914016708470ec8  unavailable        NaN
2040  ed3efbd3a87bea76c2812c66a0b32219     canceled        NaN
2074  6ad57aecbae806a7e9cc2cdb6b380711  unavailable        NaN
2121  df8282afe61008dc26c6c31011474d02     canceled        NaN
2310  8d4c637f1accf7a88a4555f02741e606     canceled        NaN
2441  9f3458f0433d4cfa472f4682654b8d49  unavailable        NaN
2457  7a9d4c7f9b068337875b95465330f2fc     canceled        NaN
2607  f0df036e9be21fc238f131bbfcdde769  unavailable        NaN
2627  86f0bcd9b426a2c1022ae317c7f27be6  unavailable        NaN
3023  98fe01bc254b759c1f2c11d77c2891d5  unavailable        NaN
3052  f56dc9034c3962e36d49fb73baa12800  unavailable        NaN
3339  0130f0f71fb0e831d18e6a3b33a3a50c  unavailable        NaN
3434  ddaec6fff982b13e7e048b627a11d6da     canceled        NaN
3468  84b8ba39037606b7b30a39d02e9e4154  unavailable        NaN

In [109]:
# Compruebo que los registros sin información de producto
# corresponden a pedidos cancelados o no disponibles.

df_final[
    df_final["product_id"].isnull()
]["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [110]:
df_final[
    (df_final["product_id"].isnull()) &
    (df_final["order_status"].isin(["created", "invoiced", "shipped"]))
][["order_id", "order_status"]]

                               order_id order_status
8423   b5359909123fa03c50bdb0cfed07f098      created
10467  dba5062fbda3af4fb6c33b1e040ca38f      created
24401  7a4df5d8cff4090e541401a20a22bb80      created
26476  a68ce1686d536ca72bd2dadc4b8671e5      shipped
62771  35de4050331c6c644cddc86f4f2d0d64      created
65603  2ce9683175cdab7d1c95bcbb3e36f478     invoiced
67142  90ab3e7d52544ec7bc3363c82689965f      created
79685  e04f1da1f48bf2bbffcf57b9824f76e1     invoiced

In [111]:
# Elimino los pedidos con estados "created", "invoiced" o "shipped"
# que no presentan ninguna línea de producto asociada.

df_final = df_final[
    ~(
        df_final["product_id"].isnull() &
        df_final["order_status"].isin(
            ["created", "invoiced", "shipped"]
        )
    )
]

In [112]:
df_final[
    df_final["product_id"].isnull()
]["order_status"].value_counts()

order_status
unavailable    603
canceled       164
Name: count, dtype: int64

In [ ]:
# Conclusión:
# Se eliminan 8 pedidos (0,008 % del total) con estados
# "created", "invoiced" o "shipped" que no presentan ninguna
# línea de producto asociada.
#
# Al tratarse de registros inconsistentes y representar un
# porcentaje insignificante del conjunto de datos, su eliminación
# no afecta al análisis y mejora la calidad del dataset final.